---
title: "Simple document"
output: html_document
---

```{r}
library(tidyverse)
library(readxl)
library(janitor)
```

# Q1 a

```{r}
q1a_df = read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N535")
q1a_df_cleannames = janitor::clean_names(q1a_df)
withoutna_df = na.omit(q1a_df_cleannames)
view(withoutna_df)
final_df = mutate(withoutna_df,sports_balls = round(sports_balls,1))
final_df
```
## Q1 b 
```{r}
my2019_df = read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "2019 Precipitation", range = "A2:B14")
my2018_df = read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet = "2018 Precipitation", range = "A2:B14")

combined_df = combine(mutate(my2019_df, year = 2019),mutate(my2018_df, year = 2018))
view(combined_df)
mutate(combined_df, Month = month.name[Month])

```
## total precipitation for 2018 is 70.33 and the median of sports balls is 9

##Q2 a
```{r}
q2_df = read_csv("data/fivethirtyeight_datasets/pols-month.csv")
q2_sep = separate(q2_df, col = mon, into=c('Year','Month', 'Day'), sep = '-')
q2_numeric = mutate(q2_sep, Month = as.numeric(Month), Year = as.numeric(Year), Day = as.numeric(Day))
mutate(q2_numeric, Month= month.name[Month])
q2_numeric = mutate(q2_numeric, President = prez_gop)
q2_numeric = mutate(q2_numeric, President = ifelse(President==1,"repub","demo"))
q2_numeric = select(q2_numeric, -Day)
q2_numeric = select(q2_numeric, -prez_gop)
q2_numeric = select(q2_numeric, -prez_dem)
q2_numeric

```

##Q2 b
```{r}
q2b_df = read_csv("data/fivethirtyeight_datasets/snp.csv")
q2b_sep = separate(q2b_df, col = date, into=c('Month','Day', 'Year'), sep = '/')
q2b_numeric = mutate(q2b_sep, Month = as.numeric(Month), Year = as.numeric(Year), Day = as.numeric(Day))
mutate(q2b_numeric, Month= month.name[Month])
q2b_numeric = select(q2b_numeric, -Day)
q2b_numeric = relocate(q2b_numeric,Year, .before = Month)
q2b_numeric = mutate(q2b_numeric, Year = ifelse(Year<20, Year+2000, Year+1900))
q2b_numeric

```

##Q2 c
```{r}
q2c_df = read_csv("data/fivethirtyeight_datasets/unemployment.csv")
tidy_verse = 
  q2c_df %>%
  pivot_longer(
    Jan:Dec,
    names_to = "Month",
    values_to = "Unemployment"
  )
view(tidy_verse)

final_set1 = merge(q2_numeric, q2b_numeric, by = c("Year"))
view(final_set1)
final = merge(final_set1,tidy_verse,by = c("Year"))
final

```

##Q3
```{r}
q3a_df = read_csv("data/Popular_Baby_Names.csv")
q3a_df = janitor::clean_names(q3a_df)
q3a_df = distinct(q3a_df)
Olivia_df = filter(q3a_df, childs_first_name=="Olivia")
Olivia_df
q3c_df = filter(q3a_df, gender == "MALE", ethnicity == "WHITE NON HISPANIC", year_of_birth == 2016)
q3c_df
ggplot(q3c_df, aes(x = rank, y = childs_first_name))+ geom_point()
```